import type { ApiDocsData } from '@livingdocs/shared';

/**
 * Generate API documentation from route data
 */
export function generateApiDocs(data: ApiDocsData): string {
  const sections: string[] = [];

  // Header
  sections.push(`# ${data.project.name} - API Documentation`);
  sections.push('');
  sections.push(`> Last updated: ${new Date().toISOString().split('T')[0]}`);
  sections.push('');

  // Group routes by framework
  const routesByFramework = new Map<string, typeof data.routes>();
  for (const route of data.routes) {
    if (!routesByFramework.has(route.framework)) {
      routesByFramework.set(route.framework, []);
    }
    routesByFramework.get(route.framework)!.push(route);
  }

  // Generate docs for each framework
  for (const [framework, routes] of routesByFramework) {
    sections.push(`## ${framework.toUpperCase()} Routes`);
    sections.push('');

    // Group by path
    const routesByPath = new Map<string, typeof routes>();
    for (const route of routes) {
      if (!routesByPath.has(route.path)) {
        routesByPath.set(route.path, []);
      }
      routesByPath.get(route.path)!.push(route);
    }

    for (const [path, pathRoutes] of routesByPath) {
      sections.push(`### \`${path}\``);
      sections.push('');

      for (const route of pathRoutes) {
        // Method badge
        const methodBadge = getMethodBadge(route.method);
        sections.push(`#### ${methodBadge} ${route.method}`);
        sections.push('');

        // Description
        if (route.description) {
          sections.push(route.description);
          sections.push('');
        }

        // Handler
        sections.push(`**Handler:** \`${route.handler}\``);
        sections.push('');

        // Middleware
        if (route.middleware && route.middleware.length > 0) {
          sections.push('**Middleware:**');
          sections.push('');
          for (const mw of route.middleware) {
            sections.push(`- \`${mw}\``);
          }
          sections.push('');
        }

        // Request Schema
        if (route.requestSchema) {
          sections.push('**Request:**');
          sections.push('');
          sections.push('```typescript');
          sections.push(route.requestSchema);
          sections.push('```');
          sections.push('');
        }

        // Response Schema
        if (route.responseSchema) {
          sections.push('**Response:**');
          sections.push('');
          sections.push('```typescript');
          sections.push(route.responseSchema);
          sections.push('```');
          sections.push('');
        }

        sections.push('---');
        sections.push('');
      }
    }
  }

  // Summary
  sections.push('## Summary');
  sections.push('');
  sections.push(`- **Total Endpoints:** ${data.routes.length}`);
  sections.push(`- **Frameworks:** ${Array.from(routesByFramework.keys()).join(', ')}`);
  sections.push('');

  // Footer
  sections.push('---');
  sections.push('');
  sections.push('*This API documentation was automatically generated by [LivingDocs](https://github.com/livingdocs/livingdocs).*');
  sections.push('');

  return sections.join('\n');
}

/**
 * Get a colored badge for HTTP method
 */
function getMethodBadge(method: string): string {
  const badges: Record<string, string> = {
    GET: '🟢',
    POST: '🔵',
    PUT: '🟠',
    DELETE: '🔴',
    PATCH: '🟡',
    OPTIONS: '⚪',
    HEAD: '⚫',
  };
  return badges[method] || '⚪';
}
