import type { ArchitectureData } from '@livingdocs/shared';

/**
 * Generate architecture.md from project data
 */
export function generateArchitecture(data: ArchitectureData): string {
  const sections: string[] = [];

  // Header
  sections.push(`# ${data.project.name} - Architecture Documentation`);
  sections.push('');
  sections.push(`> Last updated: ${new Date().toISOString().split('T')[0]}`);
  sections.push('');

  // System Overview
  sections.push('## System Overview');
  sections.push('');
  sections.push(data.overview);
  sections.push('');

  // Architecture Diagrams
  sections.push('## Architecture Diagrams');
  sections.push('');

  // Dependency Diagram
  sections.push('### Dependency Graph');
  sections.push('');
  sections.push('```mermaid');
  sections.push(data.diagrams.dependency);
  sections.push('```');
  sections.push('');

  // Service Map
  if (data.diagrams.serviceMap) {
    sections.push('### Service Map');
    sections.push('');
    sections.push('```mermaid');
    sections.push(data.diagrams.serviceMap);
    sections.push('```');
    sections.push('');
  }

  // Module Breakdown
  sections.push('## Module Breakdown');
  sections.push('');

  for (const module of data.modules) {
    sections.push(`### ${module.name}`);
    sections.push('');
    sections.push(`**Location:** \`${module.path}\``);
    sections.push('');
    sections.push(`**Files:** ${module.fileCount}`);
    sections.push('');

    // Purpose
    sections.push('**Purpose:**');
    sections.push('');
    sections.push(module.purpose);
    sections.push('');

    // Dependencies
    if (module.dependencies.length > 0) {
      sections.push('**Dependencies:**');
      sections.push('');
      for (const dep of module.dependencies) {
        sections.push(`- \`${dep}\``);
      }
      sections.push('');
    }
  }

  // Graph Statistics
  sections.push('## Architecture Statistics');
  sections.push('');

  const nodesByType: Record<string, number> = {};
  for (const node of data.graph.nodes) {
    nodesByType[node.type] = (nodesByType[node.type] || 0) + 1;
  }

  const edgesByType: Record<string, number> = {};
  for (const edge of data.graph.edges) {
    edgesByType[edge.type] = (edgesByType[edge.type] || 0) + 1;
  }

  sections.push('### Nodes');
  sections.push('');
  for (const [type, count] of Object.entries(nodesByType)) {
    sections.push(`- **${type}:** ${count}`);
  }
  sections.push('');

  sections.push('### Relationships');
  sections.push('');
  for (const [type, count] of Object.entries(edgesByType)) {
    sections.push(`- **${type}:** ${count}`);
  }
  sections.push('');

  // Footer
  sections.push('---');
  sections.push('');
  sections.push('*This documentation was automatically generated by [LivingDocs](https://github.com/livingdocs/livingdocs).*');
  sections.push('');

  return sections.join('\n');
}
