import type { OnboardingData } from '@livingdocs/shared';

/**
 * Generate onboarding.md for new developers
 */
export function generateOnboarding(data: OnboardingData): string {
  const sections: string[] = [];

  // Header
  sections.push(`# ${data.project.name} - Developer Onboarding Guide`);
  sections.push('');
  sections.push(`> Welcome to ${data.project.name}! This guide will help you get started quickly.`);
  sections.push('');

  // Day 1 Overview
  sections.push('## Day 1 Overview');
  sections.push('');
  sections.push(data.dayOneGuide.overview);
  sections.push('');

  // Setup Steps
  sections.push('## Setup');
  sections.push('');
  let stepNumber = 1;
  for (const step of data.dayOneGuide.setupSteps) {
    sections.push(`${stepNumber}. ${step}`);
    stepNumber++;
  }
  sections.push('');

  // First Tasks
  if (data.dayOneGuide.firstTasks.length > 0) {
    sections.push('## Your First Tasks');
    sections.push('');
    sections.push('Here are some recommended tasks to help you get familiar with the codebase:');
    sections.push('');
    for (const task of data.dayOneGuide.firstTasks) {
      sections.push(`- [ ] ${task}`);
    }
    sections.push('');
  }

  // Critical Files
  sections.push('## Critical Files to Understand');
  sections.push('');
  sections.push('These files are essential to understanding how the system works:');
  sections.push('');

  // Sort by priority
  const sortedFiles = [...data.criticalFiles].sort((a, b) => {
    const priorityOrder = { high: 0, medium: 1, low: 2 };
    return priorityOrder[a.priority] - priorityOrder[b.priority];
  });

  for (const file of sortedFiles) {
    const priorityBadge = file.priority === 'high' ? '⚠️ ' : '';
    sections.push(`### ${priorityBadge}\`${file.path}\``);
    sections.push('');
    sections.push(file.purpose);
    sections.push('');
  }

  // Glossary
  if (data.glossary.length > 0) {
    sections.push('## Glossary');
    sections.push('');
    sections.push('Key terms and concepts used in this project:');
    sections.push('');

    for (const entry of data.glossary) {
      sections.push(`- **${entry.term}:** ${entry.definition}`);
    }
    sections.push('');
  }

  // Architecture Quick Reference
  sections.push('## Architecture Quick Reference');
  sections.push('');

  const fileCount = data.graph.nodes.filter(n => n.type === 'file').length;
  const moduleCount = data.graph.nodes.filter(n => n.type === 'module').length;
  const routeCount = data.graph.nodes.filter(n => n.type === 'route').length;

  sections.push(`- **Total Files:** ${fileCount}`);
  sections.push(`- **Total Modules:** ${moduleCount}`);
  sections.push(`- **API Endpoints:** ${routeCount}`);
  sections.push('');

  // Tips
  sections.push('## Tips for Success');
  sections.push('');
  sections.push('1. Start with the critical files listed above');
  sections.push('2. Use `livingdocs explain <path>` to understand any file or folder');
  sections.push('3. Run the tests to see how components interact');
  sections.push('4. Ask questions in team chat if you get stuck');
  sections.push('');

  // Footer
  sections.push('---');
  sections.push('');
  sections.push('*This onboarding guide was automatically generated by [LivingDocs](https://github.com/livingdocs/livingdocs).*');
  sections.push('');

  return sections.join('\n');
}
