import type { ReadmeData } from '@livingdocs/shared';

/**
 * Generate README.md from project data
 */
export function generateReadme(data: ReadmeData): string {
  const sections: string[] = [];

  // Header
  sections.push(`# ${data.project.name}`);
  sections.push('');
  sections.push(data.project.description);
  sections.push('');

  // Architecture Overview
  sections.push('## Architecture Overview');
  sections.push('');
  sections.push(data.architecture.summary);
  sections.push('');

  // Key Modules
  if (data.architecture.keyModules.length > 0) {
    sections.push('## Key Modules');
    sections.push('');

    for (const module of data.architecture.keyModules) {
      sections.push(`### ${module.name}`);
      sections.push('');
      sections.push(`**Path:** \`${module.path}\``);
      sections.push('');
      sections.push(`**Files:** ${module.fileCount}`);
      sections.push('');
      sections.push(module.purpose);
      sections.push('');
    }
  }

  // Getting Started
  sections.push('## Getting Started');
  sections.push('');

  // Prerequisites
  if (data.gettingStarted.prerequisites.length > 0) {
    sections.push('### Prerequisites');
    sections.push('');
    for (const prereq of data.gettingStarted.prerequisites) {
      sections.push(`- ${prereq}`);
    }
    sections.push('');
  }

  // Setup Steps
  if (data.gettingStarted.setupSteps.length > 0) {
    sections.push('### Setup');
    sections.push('');
    let stepNumber = 1;
    for (const step of data.gettingStarted.setupSteps) {
      sections.push(`${stepNumber}. ${step}`);
      stepNumber++;
    }
    sections.push('');
  }

  // Statistics
  sections.push('## Project Statistics');
  sections.push('');
  sections.push(`- **Total Files:** ${data.graph.nodes.filter(n => n.type === 'file').length}`);
  sections.push(`- **Total Modules:** ${data.graph.nodes.filter(n => n.type === 'module').length}`);
  sections.push(`- **Total Dependencies:** ${data.graph.edges.filter(e => e.type === 'imports').length}`);
  sections.push('');

  // Footer
  sections.push('---');
  sections.push('');
  sections.push('*This documentation was automatically generated by [LivingDocs](https://github.com/livingdocs/livingdocs).*');
  sections.push('');

  return sections.join('\n');
}
